version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: school-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-school_db}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - school-network

  # Backend Service
  backend:
    build: .
    container_name: school-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${MONGO_DB:-school_db}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret}
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - school-network

  # Nginx as a reverse proxy for static files and API
  nginx:
    image: nginx:alpine
    container_name: school-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/usr/share/nginx/html/assets
      - .:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - school-network

networks:
  school-network:
    driver: bridge

volumes:
  mongodb_data:
